### ISSUE TITLE
Long indexation process on big projects

### ISSUE THREAD

**Issue by martixy** [goaop/idea-plugin#14] opened 2017-08-09 17:19 UTC
With the newest PHPStorm (2017.2), this plugin gets the IDE stuck on indexing the cache dir perpetually.

Let me know if this is reproducible or if you need further info, be happy to help.

**Comment by lisachenko** [comment] 2017-08-10 10:28
Hi, I'm using 2017.2 EAP version of PHPStorm and plugin works for me without issues. I know, that with enabled plugin indexing can take more time to finish, but after index is ready, everything is working normally.

![default](https://user-images.githubusercontent.com/640114/29166566-9a71eb68-7dcf-11e7-8488-1ce76ecdf7ab.png)

Have you tried to invalidate your cache and restart your IDE?

**Comment by lisachenko** [comment] 2017-08-14 10:22
Ping

**Comment by martixy** [comment] 2017-08-14 17:32
Apologies for the delay. :)
Yes. Invalidated cache and restarted.
It indexed everything correctly once, than at some point on its subsequent refreshes it got stuck again - on the aspect cache folder.

```
PhpStorm 2017.2.1
Build #PS-172.3544.41, built on August 2, 2017
JRE: 1.8.0_152-release-915-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by lisachenko** [comment] 2017-08-23 14:59
Could you mark aspect cache directory as excluded? This should speed up processing and won't affect your project with duplicates of classes, etc.

**Comment by erickskrauch** [comment] 2017-11-12 22:31
I have the same issue, but after 1-2 mins of indexing at 100% it finally was done. Aspects cache directory already marked as excluded, so I think there is some inaccurate indexing mechanic.

```
PhpStorm 2017.2.4
Build #PS-172.4155.41, built on September 15, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

**Comment by lisachenko** [comment] 2017-11-14 07:19
Guys, unfortunately it will be hard task for me to profile what is wrong with indexing, maybe @artspb could help us to debug this issue?

**Comment by artspb** [comment] 2017-11-14 08:03
Could someone who is able to reproduce the issue please do Help | Diagnostic | Profile Indexing. As a result of this action, you'll get a snapshot. Please attach it here.

**Comment by lisachenko** [comment] 2017-11-16 11:25
@artspb how could I get a snapshot? I've reproduced long indexing on my big project, but don't know what is a snapshot.

Steps to reproduce:
1. Install "Go! AOP Framework plugin"
2. Install framework itself in your project with `composer require goaop/framework`
3. Create an aspect like this:
```php
use Go\Aop\Aspect;
use Go\Aop\Intercept\MethodInvocation;
use Go\Lang\Annotation as Pointcut;


/**
 * Test aspect
 */
class TestAspect implements Aspect
{
    /**
     *
     * @Pointcut\Before("execution(public **->*(*))")
     * @param MethodInvocation $invocation
     */
    public function beforePublicGttMethods(MethodInvocation $invocation)
    {
    }
}
```

After that: 
1. `Help | Diagnostic | Profile Indexing`
2. `File | Invalidate caches / Restart` => Invalidate and restart
3. ..restart...
4. Very long indexing of project.
5. Shapshot???

**Comment by lisachenko** [comment] 2017-11-16 11:38
@artspb I've attached [system log for IDE](https://github.com/goaop/idea-plugin/files/1478356/idea.log). Interesting lines are:
```
2017-11-16 13:50:22,444 [  34345]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 5678ms; general responsiveness: ok; EDT responsiveness: ok 
2017-11-16 13:50:22,460 [  34361]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 23159 files to update 
2017-11-16 13:54:27,427 [ 279328]   INFO - ellij.vfs.persistent.FSRecords - Contents:16384 of 137340756, reuses:2388 of 2126499 for 1172 
2017-11-16 13:55:45,957 [ 357858]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 323497ms; general responsiveness: 33/289 sluggish, 4/289 very slow; EDT responsiveness: 9/308 sluggish 
```
There is clear 5 minute lag for indexation, but I don't know how to optimize this and where to look for additional details that can help you.

**Comment by artspb** [comment] 2017-11-16 12:04
@lisachenko Yeah makes sense... There's no way to stop profiling when indexing is indefinite. We'll add a stop action. Meanwhile, you can use tips from this article https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems And in any case, I'll use the steps you've provided to reproduce it myself.

**Comment by artspb** [comment] 2017-11-16 12:20
The first finding is an exception  thrown in 2018.1 (not yet publicly available):
<details>
  <summary>Index com.aopphp.go.annotation.pointcuts deserialization violates equals / hashCode contract for Value parameter </summary>
<pre><code>
java.lang.Throwable: Index com.aopphp.go.annotation.pointcuts deserialization violates equals / hashCode contract for Value parameter
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.util.indexing.impl.MapReduceIndex.checkValuesHaveProperEqualsAndHashCode(MapReduceIndex.java:355)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:272)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:99)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:214)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1649)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$20(FileBasedIndexImpl.java:1585)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:523)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1544)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1532)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:109)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:227)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1128)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:487)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:240)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:316)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)</code></pre></details>

**Comment by lisachenko** [comment] 2017-11-16 12:39
> Index com.aopphp.go.annotation.pointcuts deserialization violates equals / hashCode contract for Value parameter 

Could you please describe how to fix this?

I'm storing complex objects (pointcuts) in the index because it just worked for me, maybe something should be changed? Typically, all indexes are simple (eg strings and keys), is it ok for index to store any complex objects?

**Comment by artspb** [comment] 2017-11-16 12:41
The second finding is ineffective implementation of `com.aopphp.go.util.PluginUtil#getFileUseImports`. You walk the tree but never stop the process. The problem is that your visitor will touch each and every PSI element in the file what is obviously not needed and extremely expensive especially during indexing. Every time using a recursive visitor you should be very careful. We always try to avoid them.

Back to imports, you don't really need a visitor to collect them. `use` statements are only allowed on the first level of a file or namespace. Thus you only need to check those places. But I would suggest you using our util method for this `com.jetbrains.php.codeInsight.PhpCodeInsightUtil#collectImports`. If you still decide to have your own implementation, please keep in mind that currently, your code collects not only usual imports but also trait imports. They share the same PSI element. The `com.jetbrains.php.lang.psi.elements.PhpUse#isTraitImport` method helps to distinguish them.

![getfileuseimports](https://user-images.githubusercontent.com/391485/32891375-9798a4ae-cad2-11e7-95e8-514d43c6ea1e.png)

**Comment by lisachenko** [comment] 2017-11-16 12:46
Your detailed comments are great! I haven't expert skills in Java and IDE, so many things aren't done right, because I just didn't know how to do this previously. And your expert advices about plugin's code are very important for me.

If you could describe all possible bad places in my code and possible ways for solving them, I'll try to fix them and make plugin more stable and efficient.

**Comment by artspb** [comment] 2017-11-16 12:46
Additionally, when you implement the fix I would recommend you to repeat the following steps several times:
1. Invalidate caches and restart.
2. Attach profiler when the app starts (see the instruction above).
3. Start CPU profiling.
4. Collect the snapshot (you don't need to wait if indexing stuck - just save it somewhere in the middle, usually it's enough).
5. Analyze the data, fix host spots.

The recommendation applies not only to indexing but to any activity (typing, inspections pass, etc.). This is the most efficient way to catch performance problems.

**Comment by artspb** [comment] 2017-11-16 16:11
>Could you please describe how to fix this?

`equals`/`hashCode` methods should be properly implemented for every class which is a key or value of an index (see #15).

>I'm storing complex objects (pointcuts) in the index because it just worked for me, maybe something should be changed? Typically, all indexes are simple (eg strings and keys), is it ok for index to store any complex objects?

In general, I would recommend avoiding storing binaries in the index. It takes longer to serialize/deserialize them, they're uncompressible thus can't be stored efficiently. On the other hand, premature optimization is the root of all evil. Thus it's better from my point of view to concentrate on real performance problems. When it becomes clear that the storage type is a bottleneck only then it should be re-written accordingly.

>If you could describe all possible bad places in my code and possible ways for solving them, I'll try to fix them and make plugin more stable and efficient.

Code review is a hard and time-consuming task by itself. Without knowing a domain it becomes even more complicated. Thus for me, it's better if we continue working in a question-answer manner. I'll be glad to answer your specific questions.

Additionally, I highly recommend using a profiler on a regular basis. It is important to spot slow places as fast as possible to improve them before a laptop will burn someone's knees ;)

**Closed as completed** 2017-11-19 09:31 UTC
Labels: enhancement, performance
